# projector_type: "Stereographic"
# mgrs_origin:
#   latitude: 35.61739731
#   longitude: 139.7797546
#   altitude: 2.0
projector_type: "TransverseMercator"
mgrs_origin:
  latitude: 35.61739731
  longitude: 139.7797546
  altitude: 2.0
